# Generated by Django 3.2.4 on 2021-08-16 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_auto_20210725_2225'),
        ('authapp', '0008_alter_shopuser_activation_key_expires'),
    ]

    operations = [
    ]
