# Generated by Django 3.2.4 on 2021-08-16 22:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0009_merge_20210816_2228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 18, 22, 32, 0, 490912)),
        ),
    ]
